---
flowdock-concourse-notification-resource-boshrelease/rootfs.tar:
  object_id: 117162da-b42d-41e9-8708-1edc56b52e3b
  sha: !binary |-
    YmE0YWUxMjdjYTViOTdlNWNhZTJlYjA3YTk5ZDE3N2YzN2ExZmM0NQ==
  size: 157037056
