---
flowdock-concourse-notification-resource/rootfs.tar:
  object_id: 83756a2a-0412-46ee-93f4-e68fb6eb4c43
  sha: !binary |-
    MWEwYjMyZmEwMGZkMTYxMTY0MzMzYWY4MTBhMzBmMzI1MzY4MWQxYw==
  size: 157037056
flowdock-concourse-notification-resource-boshrelease/rootfs.tar:
  object_id: dc354f0a-43de-4a6e-826a-a74d3532abf7
  sha: !binary |-
    NmU4MzM0YjdkOGQ3MDBkMjkxZGZiZDhlZDAyNDc3YzAwZDlmZDMyZg==
  size: 157037056
