---
flowdock-concourse-notification-resource/rootfs.tar:
  object_id: 48a5d164-cbef-422d-b501-b6b652dd3225
  sha: !binary |-
    NmE3N2E3ZmQ3MGEyYjNhMGY5MDFiMjc0MTllN2VhMDNjN2FiYmQ3ZA==
  size: 157037568
