---
flowdock-concourse-notification-resource/rootfs.tar:
  object_id: a354f354-baa6-41f0-867e-eda3f9fc0c6d
  sha: !binary |-
    OTA2NDZkNzc5ZTBhZDNlYjcwNmU0MDlhODE2YmEwYzlhZTM2MDg1ZA==
  size: 157037568
