---
flowdock-concourse-notification-resource/rootfs.tar:
  object_id: 7e980b4a-0e92-4c97-8530-6266eb91c06f
  sha: !binary |-
    ODIwZDdlYjlkMTkyMzY3NDc5ZGQwODc0MjQ3NDQ5MDczZDUwZDJhOA==
  size: 157037568
