---
flowdock-concourse-notification-resource/rootfs.tar:
  object_id: 0bd569d2-334d-415b-a41a-519c3467952b
  sha: !binary |-
    OGMxYjQ2ZjE4MmY2ZWUxOTI0NmVkZTY1YjliMzc3YzViZjliZGFkZA==
  size: 157037568
