---
flowdock-concourse-notification-resource/rootfs.tar:
  object_id: b1210e00-2423-4ec9-ac35-e70a5e322c69
  sha: !binary |-
    ZTZjOGVkMDk0Y2Q2NTRlNGRlMzAzYTBjODA0MmY5NWM2NGZlNGYzZQ==
  size: 157037568
