---
flowdock-concourse-notification-resource/rootfs.tar:
  object_id: d447528f-da02-411f-949c-24d523291e89
  sha: !binary |-
    OTU5MTk0NmVmODEyNGZlZmE5MDczOTc1MWUyMmRjNzQ3OWFlODU0Ng==
  size: 157037568
