meta:
  environment: ~

update:
  canaries: 1
  max_in_flight: 50
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000
  serial: false

jobs:
  - name: install_flowdock_resource
    templates:
    - {name: install_flowdock_resource, release: flowdock-concourse-notification-resource}
    instances: 1
    persistent_disk: 0
    resource_pool: small_z1
    networks: (( merge ))

networks: (( merge ))

properties: {}
